// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: grpc/proto/music.proto

package musicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_proto_music_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{0}
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{1}
}

func (x *IdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_grpc_proto_music_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{2}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Music struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Artista       string                 `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Music) Reset() {
	*x = Music{}
	mi := &file_grpc_proto_music_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{3}
}

func (x *Music) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Music) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Music) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

type CreateMusicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Artista       string                 `protobuf:"bytes,2,opt,name=artista,proto3" json:"artista,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMusicRequest) Reset() {
	*x = CreateMusicRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMusicRequest) ProtoMessage() {}

func (x *CreateMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMusicRequest.ProtoReflect.Descriptor instead.
func (*CreateMusicRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMusicRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreateMusicRequest) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

type UpdateMusicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Artista       string                 `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMusicRequest) Reset() {
	*x = UpdateMusicRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMusicRequest) ProtoMessage() {}

func (x *UpdateMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMusicRequest.ProtoReflect.Descriptor instead.
func (*UpdateMusicRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMusicRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMusicRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UpdateMusicRequest) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

type MusicListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Musics        []*Music               `protobuf:"bytes,1,rep,name=musics,proto3" json:"musics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicListResponse) Reset() {
	*x = MusicListResponse{}
	mi := &file_grpc_proto_music_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicListResponse) ProtoMessage() {}

func (x *MusicListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicListResponse.ProtoReflect.Descriptor instead.
func (*MusicListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{6}
}

func (x *MusicListResponse) GetMusics() []*Music {
	if x != nil {
		return x.Musics
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Idade         int32                  `protobuf:"varint,3,opt,name=idade,proto3" json:"idade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_grpc_proto_music_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *User) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Idade         int32                  `protobuf:"varint,2,opt,name=idade,proto3" json:"idade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreateUserRequest) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Idade         int32                  `protobuf:"varint,3,opt,name=idade,proto3" json:"idade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UpdateUserRequest) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_grpc_proto_music_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{10}
}

func (x *UserListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	UsuarioId     int32                  `protobuf:"varint,3,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_grpc_proto_music_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{11}
}

func (x *Playlist) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Playlist) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Playlist) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

type CreatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	UsuarioId     int32                  `protobuf:"varint,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePlaylistRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CreatePlaylistRequest) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

type UpdatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	UsuarioId     int32                  `protobuf:"varint,3,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylistRequest) Reset() {
	*x = UpdatePlaylistRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistRequest) ProtoMessage() {}

func (x *UpdatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePlaylistRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlaylistRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UpdatePlaylistRequest) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

type PlaylistListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*Playlist            `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistListResponse) Reset() {
	*x = PlaylistListResponse{}
	mi := &file_grpc_proto_music_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistListResponse) ProtoMessage() {}

func (x *PlaylistListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistListResponse.ProtoReflect.Descriptor instead.
func (*PlaylistListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{14}
}

func (x *PlaylistListResponse) GetPlaylists() []*Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

type AddMusicToPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    int32                  `protobuf:"varint,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	MusicaId      int32                  `protobuf:"varint,2,opt,name=musica_id,json=musicaId,proto3" json:"musica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMusicToPlaylistRequest) Reset() {
	*x = AddMusicToPlaylistRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMusicToPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMusicToPlaylistRequest) ProtoMessage() {}

func (x *AddMusicToPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMusicToPlaylistRequest.ProtoReflect.Descriptor instead.
func (*AddMusicToPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{15}
}

func (x *AddMusicToPlaylistRequest) GetPlaylistId() int32 {
	if x != nil {
		return x.PlaylistId
	}
	return 0
}

func (x *AddMusicToPlaylistRequest) GetMusicaId() int32 {
	if x != nil {
		return x.MusicaId
	}
	return 0
}

type PlaylistMusicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    int32                  `protobuf:"varint,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistMusicsRequest) Reset() {
	*x = PlaylistMusicsRequest{}
	mi := &file_grpc_proto_music_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistMusicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistMusicsRequest) ProtoMessage() {}

func (x *PlaylistMusicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_music_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistMusicsRequest.ProtoReflect.Descriptor instead.
func (*PlaylistMusicsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_music_proto_rawDescGZIP(), []int{16}
}

func (x *PlaylistMusicsRequest) GetPlaylistId() int32 {
	if x != nil {
		return x.PlaylistId
	}
	return 0
}

var File_grpc_proto_music_proto protoreflect.FileDescriptor

const file_grpc_proto_music_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/proto/music.proto\x12\x05music\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\x05Music\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x18\n" +
	"\aartista\x18\x03 \x01(\tR\aartista\"B\n" +
	"\x12CreateMusicRequest\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x18\n" +
	"\aartista\x18\x02 \x01(\tR\aartista\"R\n" +
	"\x12UpdateMusicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x18\n" +
	"\aartista\x18\x03 \x01(\tR\aartista\"9\n" +
	"\x11MusicListResponse\x12$\n" +
	"\x06musics\x18\x01 \x03(\v2\f.music.MusicR\x06musics\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x14\n" +
	"\x05idade\x18\x03 \x01(\x05R\x05idade\"=\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x14\n" +
	"\x05idade\x18\x02 \x01(\x05R\x05idade\"M\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x14\n" +
	"\x05idade\x18\x03 \x01(\x05R\x05idade\"5\n" +
	"\x10UserListResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.music.UserR\x05users\"M\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x03 \x01(\x05R\tusuarioId\"J\n" +
	"\x15CreatePlaylistRequest\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\x05R\tusuarioId\"Z\n" +
	"\x15UpdatePlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x03 \x01(\x05R\tusuarioId\"E\n" +
	"\x14PlaylistListResponse\x12-\n" +
	"\tplaylists\x18\x01 \x03(\v2\x0f.music.PlaylistR\tplaylists\"Y\n" +
	"\x19AddMusicToPlaylistRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\x05R\n" +
	"playlistId\x12\x1b\n" +
	"\tmusica_id\x18\x02 \x01(\x05R\bmusicaId\"8\n" +
	"\x15PlaylistMusicsRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\x05R\n" +
	"playlistId2\xe3\a\n" +
	"\fMusicService\x124\n" +
	"\n" +
	"ListMusics\x12\f.music.Empty\x1a\x18.music.MusicListResponse\x12*\n" +
	"\bGetMusic\x12\x10.music.IdRequest\x1a\f.music.Music\x126\n" +
	"\vCreateMusic\x12\x19.music.CreateMusicRequest\x1a\f.music.Music\x126\n" +
	"\vUpdateMusic\x12\x19.music.UpdateMusicRequest\x1a\f.music.Music\x127\n" +
	"\vDeleteMusic\x12\x10.music.IdRequest\x1a\x16.music.MessageResponse\x122\n" +
	"\tListUsers\x12\f.music.Empty\x1a\x17.music.UserListResponse\x12(\n" +
	"\aGetUser\x12\x10.music.IdRequest\x1a\v.music.User\x123\n" +
	"\n" +
	"CreateUser\x12\x18.music.CreateUserRequest\x1a\v.music.User\x123\n" +
	"\n" +
	"UpdateUser\x12\x18.music.UpdateUserRequest\x1a\v.music.User\x126\n" +
	"\n" +
	"DeleteUser\x12\x10.music.IdRequest\x1a\x16.music.MessageResponse\x12:\n" +
	"\rListPlaylists\x12\f.music.Empty\x1a\x1b.music.PlaylistListResponse\x120\n" +
	"\vGetPlaylist\x12\x10.music.IdRequest\x1a\x0f.music.Playlist\x12?\n" +
	"\x0eCreatePlaylist\x12\x1c.music.CreatePlaylistRequest\x1a\x0f.music.Playlist\x12?\n" +
	"\x0eUpdatePlaylist\x12\x1c.music.UpdatePlaylistRequest\x1a\x0f.music.Playlist\x12:\n" +
	"\x0eDeletePlaylist\x12\x10.music.IdRequest\x1a\x16.music.MessageResponse\x12N\n" +
	"\x12AddMusicToPlaylist\x12 .music.AddMusicToPlaylistRequest\x1a\x16.music.MessageResponse\x12L\n" +
	"\x12ListPlaylistMusics\x12\x1c.music.PlaylistMusicsRequest\x1a\x18.music.MusicListResponseB\x1dZ\x1btrab6/go/grpc/proto;musicpbb\x06proto3"

var (
	file_grpc_proto_music_proto_rawDescOnce sync.Once
	file_grpc_proto_music_proto_rawDescData []byte
)

func file_grpc_proto_music_proto_rawDescGZIP() []byte {
	file_grpc_proto_music_proto_rawDescOnce.Do(func() {
		file_grpc_proto_music_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_music_proto_rawDesc), len(file_grpc_proto_music_proto_rawDesc)))
	})
	return file_grpc_proto_music_proto_rawDescData
}

var file_grpc_proto_music_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_grpc_proto_music_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: music.Empty
	(*IdRequest)(nil),                 // 1: music.IdRequest
	(*MessageResponse)(nil),           // 2: music.MessageResponse
	(*Music)(nil),                     // 3: music.Music
	(*CreateMusicRequest)(nil),        // 4: music.CreateMusicRequest
	(*UpdateMusicRequest)(nil),        // 5: music.UpdateMusicRequest
	(*MusicListResponse)(nil),         // 6: music.MusicListResponse
	(*User)(nil),                      // 7: music.User
	(*CreateUserRequest)(nil),         // 8: music.CreateUserRequest
	(*UpdateUserRequest)(nil),         // 9: music.UpdateUserRequest
	(*UserListResponse)(nil),          // 10: music.UserListResponse
	(*Playlist)(nil),                  // 11: music.Playlist
	(*CreatePlaylistRequest)(nil),     // 12: music.CreatePlaylistRequest
	(*UpdatePlaylistRequest)(nil),     // 13: music.UpdatePlaylistRequest
	(*PlaylistListResponse)(nil),      // 14: music.PlaylistListResponse
	(*AddMusicToPlaylistRequest)(nil), // 15: music.AddMusicToPlaylistRequest
	(*PlaylistMusicsRequest)(nil),     // 16: music.PlaylistMusicsRequest
}
var file_grpc_proto_music_proto_depIdxs = []int32{
	3,  // 0: music.MusicListResponse.musics:type_name -> music.Music
	7,  // 1: music.UserListResponse.users:type_name -> music.User
	11, // 2: music.PlaylistListResponse.playlists:type_name -> music.Playlist
	0,  // 3: music.MusicService.ListMusics:input_type -> music.Empty
	1,  // 4: music.MusicService.GetMusic:input_type -> music.IdRequest
	4,  // 5: music.MusicService.CreateMusic:input_type -> music.CreateMusicRequest
	5,  // 6: music.MusicService.UpdateMusic:input_type -> music.UpdateMusicRequest
	1,  // 7: music.MusicService.DeleteMusic:input_type -> music.IdRequest
	0,  // 8: music.MusicService.ListUsers:input_type -> music.Empty
	1,  // 9: music.MusicService.GetUser:input_type -> music.IdRequest
	8,  // 10: music.MusicService.CreateUser:input_type -> music.CreateUserRequest
	9,  // 11: music.MusicService.UpdateUser:input_type -> music.UpdateUserRequest
	1,  // 12: music.MusicService.DeleteUser:input_type -> music.IdRequest
	0,  // 13: music.MusicService.ListPlaylists:input_type -> music.Empty
	1,  // 14: music.MusicService.GetPlaylist:input_type -> music.IdRequest
	12, // 15: music.MusicService.CreatePlaylist:input_type -> music.CreatePlaylistRequest
	13, // 16: music.MusicService.UpdatePlaylist:input_type -> music.UpdatePlaylistRequest
	1,  // 17: music.MusicService.DeletePlaylist:input_type -> music.IdRequest
	15, // 18: music.MusicService.AddMusicToPlaylist:input_type -> music.AddMusicToPlaylistRequest
	16, // 19: music.MusicService.ListPlaylistMusics:input_type -> music.PlaylistMusicsRequest
	6,  // 20: music.MusicService.ListMusics:output_type -> music.MusicListResponse
	3,  // 21: music.MusicService.GetMusic:output_type -> music.Music
	3,  // 22: music.MusicService.CreateMusic:output_type -> music.Music
	3,  // 23: music.MusicService.UpdateMusic:output_type -> music.Music
	2,  // 24: music.MusicService.DeleteMusic:output_type -> music.MessageResponse
	10, // 25: music.MusicService.ListUsers:output_type -> music.UserListResponse
	7,  // 26: music.MusicService.GetUser:output_type -> music.User
	7,  // 27: music.MusicService.CreateUser:output_type -> music.User
	7,  // 28: music.MusicService.UpdateUser:output_type -> music.User
	2,  // 29: music.MusicService.DeleteUser:output_type -> music.MessageResponse
	14, // 30: music.MusicService.ListPlaylists:output_type -> music.PlaylistListResponse
	11, // 31: music.MusicService.GetPlaylist:output_type -> music.Playlist
	11, // 32: music.MusicService.CreatePlaylist:output_type -> music.Playlist
	11, // 33: music.MusicService.UpdatePlaylist:output_type -> music.Playlist
	2,  // 34: music.MusicService.DeletePlaylist:output_type -> music.MessageResponse
	2,  // 35: music.MusicService.AddMusicToPlaylist:output_type -> music.MessageResponse
	6,  // 36: music.MusicService.ListPlaylistMusics:output_type -> music.MusicListResponse
	20, // [20:37] is the sub-list for method output_type
	3,  // [3:20] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_proto_music_proto_init() }
func file_grpc_proto_music_proto_init() {
	if File_grpc_proto_music_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_music_proto_rawDesc), len(file_grpc_proto_music_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_music_proto_goTypes,
		DependencyIndexes: file_grpc_proto_music_proto_depIdxs,
		MessageInfos:      file_grpc_proto_music_proto_msgTypes,
	}.Build()
	File_grpc_proto_music_proto = out.File
	file_grpc_proto_music_proto_goTypes = nil
	file_grpc_proto_music_proto_depIdxs = nil
}
