server.port=8091
cxf.path=/
spring.datasource.url=jdbc:postgresql://localhost:5432/musicas_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
